"""Added resolution fields to comment model

Revision ID: 070a1040097e
Revises: 3b39b875c37c
Create Date: 2026-02-17 15:28:20.719039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '070a1040097e'
down_revision: Union[str, Sequence[str], None] = '3b39b875c37c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.add_column('comments', sa.Column('resolved_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'comments', 'users', ['resolved_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'resolved_by')
    op.drop_column('comments', 'resolved_at')
    # ### end Alembic commands ###
