"""Add unique constraint on published_versions scheme_id and version_label

Revision ID: 1029497287bd
Revises: 07616af9e487
Create Date: 2026-01-07 11:09:49.077802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1029497287bd'
down_revision: Union[str, Sequence[str], None] = '07616af9e487'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_published_versions_scheme_label', 'published_versions', ['scheme_id', 'version_label'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_published_versions_scheme_label', 'published_versions', type_='unique')
    # ### end Alembic commands ###
