"""Change change_events scheme_id to SET NULL on delete

Revision ID: 1a6d55762dd6
Revises: adb7edef5e02
Create Date: 2026-01-07 10:43:57.749500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a6d55762dd6'
down_revision: Union[str, Sequence[str], None] = 'adb7edef5e02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('change_events', 'scheme_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('change_events_scheme_id_fkey'), 'change_events', type_='foreignkey')
    op.create_foreign_key(None, 'change_events', 'concept_schemes', ['scheme_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'change_events', type_='foreignkey')
    op.create_foreign_key(op.f('change_events_scheme_id_fkey'), 'change_events', 'concept_schemes', ['scheme_id'], ['id'], ondelete='CASCADE')
    op.alter_column('change_events', 'scheme_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
