"""add property_domain_class join table

Revision ID: 28243e09efe4
Revises: 3e71deffedbf
Create Date: 2026-03-06 16:00:04.642816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28243e09efe4'
down_revision: Union[str, Sequence[str], None] = '3e71deffedbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_domain_class',
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['ontology_classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('property_id', 'class_id')
    )
    op.create_index('ix_property_domain_class_class_id', 'property_domain_class', ['class_id'])
    # ### end Alembic commands ###

    # Backfill: copy existing domain_class scalar into join rows
    op.execute("""
        INSERT INTO property_domain_class (property_id, class_id)
        SELECT p.id, oc.id
        FROM properties p
        JOIN ontology_classes oc
            ON oc.uri = p.domain_class
            AND oc.project_id = p.project_id
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_property_domain_class_class_id', 'property_domain_class')
    op.drop_table('property_domain_class')
    # ### end Alembic commands ###
