"""Add concept_related association table

Revision ID: 30932a6be515
Revises: e5b8a4eacd00
Create Date: 2026-01-07 09:32:06.085092

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "30932a6be515"
down_revision: Union[str, Sequence[str], None] = "e5b8a4eacd00"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "concept_related",
        sa.Column("concept_id", sa.Uuid(), nullable=False),
        sa.Column("related_concept_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["concept_id"], ["concepts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["related_concept_id"], ["concepts.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("concept_id", "related_concept_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("concept_related")
    # ### end Alembic commands ###
