"""add class_superclass join table

Revision ID: 3e71deffedbf
Revises: c2c43b548cf7
Create Date: 2026-03-04 19:57:48.401344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e71deffedbf'
down_revision: Union[str, Sequence[str], None] = 'c2c43b548cf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_superclass',
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('superclass_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['ontology_classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superclass_id'], ['ontology_classes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('class_id', 'superclass_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('class_superclass')
    # ### end Alembic commands ###
