"""add range_class_id to properties

Revision ID: 6fb4ab977cfe
Revises: 70a40f327144
Create Date: 2026-02-19 16:24:13.785256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fb4ab977cfe'
down_revision: Union[str, Sequence[str], None] = '70a40f327144'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('range_class_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'properties', 'ontology_classes', ['range_class_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_column('properties', 'range_class_id')
    # ### end Alembic commands ###
