"""Added resolution fields to comment model

Revision ID: 7e9830fce9b3
Revises: f439aa87ed1d
Create Date: 2026-02-18 11:32:15.179758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e9830fce9b3'
down_revision: Union[str, Sequence[str], None] = 'f439aa87ed1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.add_column('comments', sa.Column('resolved_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'comments', 'users', ['resolved_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'resolved_by')
    op.drop_column('comments', 'resolved_at')
    # ### end Alembic commands ###
