"""add property_type column

Revision ID: 80b6ab36ba8d
Revises: 28243e09efe4
Create Date: 2026-03-06 21:14:34.190844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80b6ab36ba8d'
down_revision: Union[str, Sequence[str], None] = '28243e09efe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('property_type', sa.String(length=20), server_default='object', nullable=False))
    # ### end Alembic commands ###

    # Backfill: properties with range_datatype are "datatype", rest default to "object".
    # rdf:Property types require re-import to get correct type.
    op.execute("""
        UPDATE properties SET property_type = 'datatype'
        WHERE range_datatype IS NOT NULL
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'property_type')
    # ### end Alembic commands ###
