"""Add class_restriction table and concept_type_uris column (#144)

Revision ID: 86d7baaf2296
Revises: 80b6ab36ba8d
Create Date: 2026-03-09 11:47:30.156533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86d7baaf2296'
down_revision: Union[str, Sequence[str], None] = '80b6ab36ba8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_restrictions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('on_property_uri', sa.String(length=2048), nullable=False),
    sa.Column('restriction_type', sa.String(length=50), nullable=False),
    sa.Column('value_uri', sa.String(length=2048), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['ontology_classes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'on_property_uri', 'restriction_type', 'value_uri', name='uq_class_restriction')
    )
    op.add_column('concepts', sa.Column('concept_type_uris', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('concepts', 'concept_type_uris')
    op.drop_table('class_restrictions')
    # ### end Alembic commands ###
