"""make project namespace required

Revision ID: 9817166d9a32
Revises: 476b21d7dd14
Create Date: 2026-03-11 15:06:28.894072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9817166d9a32'
down_revision: Union[str, Sequence[str], None] = '476b21d7dd14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Backfill existing null namespaces with a placeholder
    op.execute(
        sa.text(
            "UPDATE projects SET namespace = 'https://example.org/' || id "
            "WHERE namespace IS NULL"
        )
    )
    op.alter_column('projects', 'namespace',
               existing_type=sa.VARCHAR(length=2048),
               nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'namespace',
               existing_type=sa.VARCHAR(length=2048),
               nullable=True)
    # ### end Alembic commands ###
