"""Remove versioning tables and columns

Revision ID: a5b8b1a6caeb
Revises: ae2cfe4c0f31
Create Date: 2026-02-16 15:04:21.243668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5b8b1a6caeb'
down_revision: Union[str, Sequence[str], None] = 'ae2cfe4c0f31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_published_versions_scheme_id'), table_name='published_versions')
    op.drop_table('published_versions')
    op.drop_column('concept_schemes', 'version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concept_schemes', sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_table('published_versions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('scheme_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('version_label', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['scheme_id'], ['concept_schemes.id'], name=op.f('published_versions_scheme_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('published_versions_pkey')),
    sa.UniqueConstraint('scheme_id', 'version_label', name=op.f('uq_published_versions_scheme_label'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_published_versions_scheme_id'), 'published_versions', ['scheme_id'], unique=False)
    # ### end Alembic commands ###
