"""make published_at non-nullable

Revision ID: ad2e0561b276
Revises: c6371081056f
Create Date: 2026-02-24 10:01:35.886387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad2e0561b276'
down_revision: Union[str, Sequence[str], None] = 'c6371081056f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Backfill any NULL rows before adding the constraint
    op.execute("UPDATE published_versions SET published_at = now() WHERE published_at IS NULL")
    op.alter_column('published_versions', 'published_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('published_versions', 'published_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###
