"""Make concept identifier non-nullable with full unique index

Revision ID: b367fee3d2ab
Revises: 9817166d9a32
Create Date: 2026-03-14 10:13:08.766693

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b367fee3d2ab'
down_revision: str | Sequence[str] | None = '9817166d9a32'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('concepts', 'identifier',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('uq_concept_scheme_identifier'), table_name='concepts', postgresql_where='(identifier IS NOT NULL)')
    op.create_unique_constraint('uq_concept_scheme_identifier', 'concepts', ['scheme_id', 'identifier'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_concept_scheme_identifier', 'concepts', type_='unique')
    op.create_index(op.f('uq_concept_scheme_identifier'), 'concepts', ['scheme_id', 'identifier'], unique=True, postgresql_where='(identifier IS NOT NULL)')
    op.alter_column('concepts', 'identifier',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
