"""replace response jsonb with explicit columns

Revision ID: c2c43b548cf7
Revises: f384033dffca
Create Date: 2026-02-25 16:10:44.993756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2c43b548cf7'
down_revision: Union[str, Sequence[str], None] = 'f384033dffca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('response_content', sa.Text(), nullable=True))
    op.add_column('feedback', sa.Column('responded_by', sa.Uuid(), nullable=True))
    op.add_column('feedback', sa.Column('responded_by_name', sa.String(length=255), nullable=True))
    op.add_column('feedback', sa.Column('responded_at', sa.DateTime(), nullable=True))
    op.add_column('feedback', sa.Column('status_changed_at', sa.DateTime(), nullable=True))
    op.add_column('feedback', sa.Column('status_changed_by', sa.Uuid(), nullable=True))
    op.create_index('ix_feedback_project_status', 'feedback', ['project_id', 'deleted_at', 'status', 'created_at'], unique=False)
    op.create_foreign_key(None, 'feedback', 'users', ['status_changed_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'feedback', 'users', ['responded_by'], ['id'], ondelete='SET NULL')
    # Migrate existing JSONB response data to new columns
    op.execute("""
        UPDATE feedback
        SET response_content = response->>'content',
            responded_at = (response->>'created_at')::timestamp
        WHERE response IS NOT NULL
    """)
    op.drop_column('feedback', 'response')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_index('ix_feedback_project_status', table_name='feedback')
    op.drop_column('feedback', 'status_changed_by')
    op.drop_column('feedback', 'status_changed_at')
    op.drop_column('feedback', 'responded_at')
    op.drop_column('feedback', 'responded_by_name')
    op.drop_column('feedback', 'responded_by')
    op.drop_column('feedback', 'response_content')
    # ### end Alembic commands ###
