"""semver suffix and tz-aware datetime

Revision ID: c6371081056f
Revises: 70a40f327144
Create Date: 2026-02-19 11:22:16.601296

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c6371081056f"
down_revision: Union[str, Sequence[str], None] = "70a40f327144"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "published_versions",
        "published_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.drop_index(
        op.f("ix_one_draft_per_project"),
        table_name="published_versions",
        postgresql_where="(NOT finalized)",
    )

    # Recreate version_sort_key with pre-release-aware computed expression
    op.drop_index(
        "ix_latest_version_lookup",
        table_name="published_versions",
        postgresql_where="finalized",
    )
    op.drop_column("published_versions", "version_sort_key")
    op.add_column(
        "published_versions",
        sa.Column(
            "version_sort_key",
            postgresql.ARRAY(sa.Integer()),
            sa.Computed(
                "CASE WHEN version LIKE '%%-pre%%' THEN"
                " string_to_array(split_part(version, '-pre', 1), '.')::int[]"
                " || ARRAY[split_part(version, '-pre', 2)::int]"
                " ELSE"
                " string_to_array(version, '.')::int[] || ARRAY[2147483647]"
                " END",
                persisted=True,
            ),
            nullable=False,
        ),
    )
    op.create_index(
        "ix_latest_version_lookup",
        "published_versions",
        ["project_id", "version_sort_key"],
        unique=False,
        postgresql_where="finalized",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Revert version_sort_key to simple expression without pre-release handling
    op.drop_index(
        "ix_latest_version_lookup",
        table_name="published_versions",
        postgresql_where="finalized",
    )
    op.drop_column("published_versions", "version_sort_key")
    op.add_column(
        "published_versions",
        sa.Column(
            "version_sort_key",
            postgresql.ARRAY(sa.Integer()),
            sa.Computed(
                "string_to_array(version, '.')::int[]",
                persisted=True,
            ),
            nullable=False,
        ),
    )
    op.create_index(
        "ix_latest_version_lookup",
        "published_versions",
        ["project_id", "version_sort_key"],
        unique=False,
        postgresql_where="finalized",
    )

    op.create_index(
        op.f("ix_one_draft_per_project"),
        "published_versions",
        ["project_id"],
        unique=True,
        postgresql_where="(NOT finalized)",
    )
    op.alter_column(
        "published_versions",
        "published_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
