"""Added resolution fields to comment model

Revision ID: d48ae13b7bf6
Revises: ae2cfe4c0f31
Create Date: 2026-02-16 11:46:15.744165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd48ae13b7bf6'
down_revision: Union[str, Sequence[str], None] = 'ae2cfe4c0f31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.add_column('comments', sa.Column('resolved_by', sa.Uuid(), nullable=True))
    op.create_foreign_key("fk_resolved_by_user", 'comments', 'users', ['resolved_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_resolved_by_user", 'comments', type_='foreignkey')
    op.drop_column('comments', 'resolved_by')
    op.drop_column('comments', 'resolved_at')
    # ### end Alembic commands ###
