"""Add alt_labels to concepts

Revision ID: e5b8a4eacd00
Revises: f04440e8fece
Create Date: 2026-01-07 00:21:53.814242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5b8a4eacd00'
down_revision: Union[str, Sequence[str], None] = 'f04440e8fece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concepts', sa.Column('alt_labels', postgresql.ARRAY(sa.String()), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('concepts', 'alt_labels')
    # ### end Alembic commands ###
