"""Add identifier field to concepts

Revision ID: f04440e8fece
Revises: 1d9116da1d4b
Create Date: 2026-01-06 22:53:59.258763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f04440e8fece'
down_revision: Union[str, Sequence[str], None] = '1d9116da1d4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concepts', sa.Column('identifier', sa.String(length=255), nullable=True))
    op.drop_column('concepts', 'uri')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concepts', sa.Column('uri', sa.VARCHAR(length=2048), autoincrement=False, nullable=True))
    op.drop_column('concepts', 'identifier')
    # ### end Alembic commands ###
