"""add published_versions table

Revision ID: f439aa87ed1d
Revises: 3b39b875c37c
Create Date: 2026-02-16 18:05:00.328627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f439aa87ed1d'
down_revision: Union[str, Sequence[str], None] = '3b39b875c37c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('published_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('finalized', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('previous_version_id', sa.Uuid(), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version_sort_key', postgresql.ARRAY(sa.Integer()), sa.Computed("string_to_array(version, '.')::int[]", persisted=True), nullable=False),
    sa.ForeignKeyConstraint(['previous_version_id'], ['published_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version', name='uq_published_version_per_project')
    )
    op.create_index('ix_latest_version_lookup', 'published_versions', ['project_id', 'version_sort_key'], unique=False, postgresql_where='finalized')
    op.create_index('ix_one_draft_per_project', 'published_versions', ['project_id'], unique=True, postgresql_where='NOT finalized')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_one_draft_per_project', table_name='published_versions', postgresql_where='NOT finalized')
    op.drop_index('ix_latest_version_lookup', table_name='published_versions', postgresql_where='finalized')
    op.drop_table('published_versions')
    # ### end Alembic commands ###
